name: .NET 9 Build and Test

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main
      - develop  # Trigger on pull request to 'main' or 'develop' branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --logger trx --results-directory TestResults --collect:"XPlat Code Coverage"

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: CodeCoverage
          path: coverage-report
